### PR TITLE
disable dllexport from static builds.

### PR DESCRIPTION
**Pull request by sezero**
I think this is also a better solution than PR/15, so:
Closes: https://github.com/icculus/physfs/pull/15

### CODE REVIEW

**Comment by sezero** [comment]
Now I can't make this to work... what am I missing..

**Comment by icculus** [comment]
> Now I can't make this to work... what am I missing..

https://cmake.org/cmake/help/v3.23/prop_tgt/DEFINE_SYMBOL.html

"when compiling sources in a shared library"

Maybe `target_compile_definitions` instead?

**Comment by icculus** [comment]
Or `set_target_propertes` with [COMPILE_DEFINITIONS](https://cmake.org/cmake/help/latest/prop_tgt/COMPILE_DEFINITIONS.html#compile-definitions) ...?

**Comment by sezero** [comment]
Same thing I do works in SDL_sound though - what the hell is happening here, I don't know.

**Comment by sezero** [comment]
> "when compiling sources in a shared library"

Yes, that seems to be what I missed.

**Comment by SpaceIm** [comment]
The logic is still wrong at consume time if static.

**Comment by sezero** [comment]
#15 disabled user's ability to override `PHYSFS_DECL`. What is really wrong with https://github.com/icculus/physfs/commit/14691399cd55e2e6408b2b2d07084881885a30bb?

**Comment by SpaceIm** [comment]
> What is really wrong with https://github.com/icculus/physfs/commit/14691399cd55e2e6408b2b2d07084881885a30bb?

`PHYSFS_DECL` is `__declspec(dllexport)` at consume time, which is wrong both for static & shared.

**Comment by sezero** [comment]
Harmless though.

**Comment by SpaceIm** [comment]
it's so easy to fix that I don't understand why not doing it?

**Comment by sezero** [comment]
@icculus to decide

**Comment by SpaceIm** [comment]
Ok, I just don't want to fix this forever in conan.

**Comment by icculus** [comment]
My preference is when someone just drops the source code into their project without using our CMake files at all, more or less as a static build, they don't have to define anything extra.

Things using CMake to get a shared library--Linux distros packaging or whatever--can use that to set a compiler define when building PhysicsFS so things are marked as dllexport.

So that leaves one question: What do we do for people that are using the shared library in their app and need to know that those functions should be dllimport, but might just be building against the headers without a special define set. Is it safe for these things to be marked as dllimport in this case, whether they're actually in a shared library or not?

**Comment by SpaceIm** [comment]
So https://github.com/icculus/physfs/commit/14691399cd55e2e6408b2b2d07084881885a30bb is not the correct solution, since it defines `PHYSFS_DECL` as `__declspec(dllexport)` on Windows by default.

Something like this would satisfy everybody:

```c++
#ifndef PHYSFS_DECL
#  ifndef physfs_EXPORTS
#    define PHYSFS_DECL
#  else
#    ifdef _WIN32
#      define PHYSFS_DECL __declspec(dllexport)
#    else
#      define PHYSFS_DECL __attribute__((visibility("default")))
#    endif
#  endif
#endif
```

And no definition injection in CMakeLists.

It works because CMake automatically inject `targetName_EXPORTS` as `DEFINE_SYMBOL` (when lib is shared).

I also assume that there are not global symbols in physfs, so `__declspec(dllimport)` at consume time if lib is shared can be avoided.

**Pull request closed without merging**
